package eu.dlvm.domotics.events;

/**
 * <dl>
 * <dd>LEFT_CLICK</dd>
 * <dd>RIGHT_CLICK</dd>
 * <dd>LEFT_HOLD_DOWN</dd>
 * <dd>LEFT_RELEASED</dd>
 * <dd>RIGHT_HOLD_DOWN</dd>
 * <dd>RIGHT_RELEASED</dd>
 * <dd>LEFT_WITH_RIGHTCLICK</dd>
 * <dd>RIGHT_WITH_LEFTCLICK</dd>
 */
public enum EventType {
	ON, OFF, TOGGLE, LIGHT_HIGH, LIGHT_LOW, ALARM, SAFE, UP, DOWN, TOGGLE_UP, TOGGLE_DOWN, SINGLE_CLICK, DOUBLE_CLICK, LONG_CLICK, LEFT_CLICK, RIGHT_CLICK, LEFT_HOLD_DOWN, LEFT_RELEASED, RIGHT_HOLD_DOWN, RIGHT_RELEASED, LEFT_WITH_RIGHTCLICK, RIGHT_WITH_LEFTCLICK
}